// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLA31r7FHWnUonHJQULUtchIcB5bbKOak',
    appId: '1:888943185574:web:7987dca4020093c834ae67',
    messagingSenderId: '888943185574',
    projectId: 'quaily',
    authDomain: 'quaily.firebaseapp.com',
    storageBucket: 'quaily.appspot.com',
    measurementId: 'G-BC03EKGTXB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVGA5K9wEV4apQqcprfcYKzFPTYVYZmvI',
    appId: '1:888943185574:android:d9b0dde53d2a9e5b34ae67',
    messagingSenderId: '888943185574',
    projectId: 'quaily',
    storageBucket: 'quaily.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATj-nUJWeAH8iSNDxNVwPX4gDQV9fsw2U',
    appId: '1:888943185574:ios:2ab7d381a0db404134ae67',
    messagingSenderId: '888943185574',
    projectId: 'quaily',
    storageBucket: 'quaily.appspot.com',
    androidClientId: '888943185574-a4bcpsu6nrsu0rc0hffoc13mrb153fcu.apps.googleusercontent.com',
    iosClientId: '888943185574-7kcv95nl8qg94j30t6sgdsgqnijr2fmp.apps.googleusercontent.com',
    iosBundleId: 'com.example.quaily',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATj-nUJWeAH8iSNDxNVwPX4gDQV9fsw2U',
    appId: '1:888943185574:ios:2ab7d381a0db404134ae67',
    messagingSenderId: '888943185574',
    projectId: 'quaily',
    storageBucket: 'quaily.appspot.com',
    androidClientId: '888943185574-a4bcpsu6nrsu0rc0hffoc13mrb153fcu.apps.googleusercontent.com',
    iosClientId: '888943185574-7kcv95nl8qg94j30t6sgdsgqnijr2fmp.apps.googleusercontent.com',
    iosBundleId: 'com.example.quaily',
  );
}
